from flask import Flask, jsonify

app = Flask(__name__)

# Love quotes data
love_quotes = {
    "love_quotes": [
        "I love you not only for what you are, but for what I am when I am with you.",
        "You are my sun, my moon, and all my stars.",
        "In your smile, I see something more beautiful than the stars.",
        "I am yours, don’t give myself back to me.",
        "Every love story is beautiful, but ours is my favorite.",
        "You are the peanut butter to my jelly.",
        "I could start a fire with what I feel for you.",
        "You make my heart smile.",
        "I love you to the moon and back.",
        "You are my today and all of my tomorrows.",
        "You have bewitched me, body and soul.",
        "I fell in love with you because of the million things you never knew you were doing.",
        "You’re the reason I look down at my phone and smile.",
        "My love for you is a journey, starting at forever and ending at never.",
        "You are my heart, my life, my one and only thought.",
        "If I know what love is, it is because of you.",
        "You make me want to be a better man.",
        "When I’m with you, I feel at home.",
        "You are my favorite notification.",
        "I love you more than yesterday, but less than tomorrow.",
        "You make my heart skip a beat.",
        "You are the missing piece to my puzzle.",
        "With you, I have everything.",
        "I love you more than words can say.",
        "You are my greatest adventure.",
        "You are my dream come true.",
        "I didn’t believe in love at first sight until I met you.",
        "You are the love of my life and the life of my love.",
        "You are my happily ever after.",
        "Being with you feels like coming home.",
        "You are my sunshine on a rainy day.",
        "Your love is the light that guides me.",
        "I cherish every moment spent with you.",
        "You are my forever and always.",
        "You are my favorite hello and my hardest goodbye.",
        "You complete me.",
        "I love you not just for who you are, but for who I am when I'm with you.",
        "You are my love song.",
        "Together is my favorite place to be.",
        "You are the best thing that ever happened to me.",
        "I could spend forever in your arms.",
        "You are my soulmate.",
        "I love you for all that you are, all that you have been, and all that you will be.",
        "You are the reason I believe in love.",
        "I love you more than anything in this world.",
        "You are my heart's desire.",
        "If I had to choose between loving you and breathing, I would use my last breath to say I love you.",
        "You light up my life.",
        "Your smile is my favorite thing.",
        "I love you more than the stars in the sky.",
        "You are my treasure.",
        "You are the love that came without a warning.",
        "You are the reason I wake up every morning.",
        "I will love you until the stars go out, and the tides no longer turn.",
        "You are my greatest gift.",
        "Your love is my anchor.",
        "You are my paradise.",
        "I love you fiercely, unapologetically, and completely.",
        "You are my moonlight.",
        "You have a place in my heart no one else could ever have.",
        "You are the love I never saw coming.",
        "You are the reason I look forward to every day.",
        "I love you endlessly.",
        "You are my dream come true.",
        "You are my favorite person.",
        "You are the spark that ignites my heart.",
        "You are my greatest strength.",
        "You are the melody in my heart.",
        "You have my whole heart.",
        "You are my reason to smile.",
        "I love you more than you will ever know.",
        "You are my greatest inspiration.",
        "You are my best friend and my greatest love.",
        "I love you with all my heart and soul.",
        "You are my safe place.",
        "You are the light in my life.",
        "I love you like a love song.",
        "You are my everything.",
        "You are the reason I believe in magic.",
        "I love you beyond words.",
        "You are my greatest joy.",
        "You are my heart's wish.",
        "You make every day brighter.",
        "You are my favorite person to do nothing with.",
        "You are the one I want to grow old with.",
        "You are my greatest adventure.",
        "You are the reason I am who I am.",
        "I love you more than yesterday, but less than tomorrow.",
        "You are the sunshine that brightens my day.",
        "You are my heart's desire.",
        "You are my dream come true.",
        "I love you for all that you are.",
        "You are my forever love.",
        "You are my safe haven.",
        "You make my heart sing.",
        "You are my love story.",
        "You are the flutter in my heart.",
        "You are my one and only.",
        "You are the best part of my day.",
        "You are my heart's delight.",
        "You are the reason I smile.",
        "You are my love, my life.",
        "You are the poetry in my heart.",
    ]
}


@app.route("/api/love-quotes", methods=["GET"])
def get_love_quotes():
    return jsonify(love_quotes)


if __name__ == "__main__":
    app.run(debug=True)
